image: deanhigh/techan:latest

pipelines:
  default:
    - step:
        script:
          - pip install -U coverage pylint
          - pylint ta || exit 0
          - nosetests --with-coverage --cover-package=ta