mongo:
  image: mongo
  volumes:
    - ./.data/mongo/:/data/db
  ports:
    - "27017:27017"
mongoclient:
  image: mongoclient/mongoclient
  ports:
    - "3000:3000"
  links:
    - mongo
nginx:
  image: nginx
  volumes:
    - ./ui/static:/usr/share/nginx/html
    - ./etc/nginx/:/etc/nginx
  ports:
    - "80:80"
    - "443:443"

